[dev]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test"
  status = 200

[[redirects]]
  from = "/api/generate"
  to = "/.netlify/functions/generate"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
