[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
    'npm install --include=optional',
    'cd server && npm install',
    'cd client && npm install --include=optional'
]

[phases.build]
cmds = [
    'cd server && npm run build',
    'cd client && npm run build'
]

[start]
cmd = 'cd server && npm start'
