[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
    'npm ci --include=optional',
    'cd server && npm ci',
    'cd client && npm ci'
]

[phases.build]
cmds = [
    'cd server && npm run build',
    'cd client && npm run build'
]

[start]
cmd = 'cd server && npm start'
